
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 13;
  public static final int LTE = 16;
  public static final int UMINUS = 32;
  public static final int LPAREN = 26;
  public static final int INT = 5;
  public static final int MINUS = 11;
  public static final int TILDE = 20;
  public static final int RPAREN = 27;
  public static final int AND = 22;
  public static final int LT = 14;
  public static final int LOWER_THAN_ELSE = 9;
  public static final int OR = 21;
  public static final int BOOL = 2;
  public static final int COMMA = 25;
  public static final int ERR = 36;
  public static final int NUM = 35;
  public static final int PLUS = 10;
  public static final int ASSIGN = 23;
  public static final int IF = 3;
  public static final int ID = 34;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int error = 1;
  public static final int SCOLON = 24;
  public static final int LCURLY = 30;
  public static final int NEQ = 19;
  public static final int VOID = 7;
  public static final int EQ = 18;
  public static final int GTE = 17;
  public static final int RCURLY = 31;
  public static final int TRUTH = 33;
  public static final int TIMES = 12;
  public static final int ELSE = 4;
  public static final int LSQUARE = 28;
  public static final int RSQUARE = 29;
  public static final int WHILE = 8;
  public static final int GT = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "IF",
  "ELSE",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "LOWER_THAN_ELSE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LT",
  "GT",
  "LTE",
  "GTE",
  "EQ",
  "NEQ",
  "TILDE",
  "OR",
  "AND",
  "ASSIGN",
  "SCOLON",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LSQUARE",
  "RSQUARE",
  "LCURLY",
  "RCURLY",
  "UMINUS",
  "TRUTH",
  "ID",
  "NUM",
  "ERR"
  };
}

